-- A case waits for its firm's payout account before it goes public.
--
-- Until now the only door out of the wizard was `live`, so a plaintiff finished
-- their case and published a campaign that could not accept a single donation:
-- the destination account is opened by their *attorney*, per case, through
-- Stripe's hosted flow, and that had not happened yet. The public page showed a
-- goal and a progress bar and a donate panel that refused — `resolvePayoutDestination`
-- has always held the line on the money, but nothing held the line on going public.
--
-- `pending_payout` is that line. The case is finished and committed, private, and
-- visible to the representing attorney so they can clear it. `draft` could not
-- serve: attorneys cannot see drafts (see `myCaseWhere`), so a case parked there
-- would wait on someone who could never learn it existed.
--
-- Additive only — no existing row changes status. Every case already `live` was
-- published under the old rule and keeps its state; a live case that still cannot
-- receive is handled where it always was, by the donate panel and the bind step.
--
-- Ordered BEFORE 'live' so the Postgres enum matches the declaration order in
-- schema/case.prisma, which is the lifecycle order. Adding a value is safe inside
-- Prisma's transaction on PG 12+ as long as the migration does not also *use* it;
-- this one does not.

-- AlterEnum
ALTER TYPE "CaseStatus" ADD VALUE 'pending_payout' BEFORE 'live';
