import "server-only";

import { env } from "@just-us/env/server";
import { del, get, put } from "@vercel/blob";
import sharp from "sharp";
import {
	isManagedPrivateAvatarUrl,
	profileAvatarBlobPath,
} from "@/lib/avatar-policy";

export const AVATAR_MAX_BYTES = 2 * 1024 * 1024;
export const AVATAR_ACCEPTED_TYPES = [
	"image/jpeg",
	"image/png",
	"image/webp",
] as const;

const AVATAR_SOURCE_FORMATS = new Set(["jpeg", "png", "webp"]);

export class AvatarValidationError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "AvatarValidationError";
	}
}

function privateAvatarBlobAuth() {
	// Deployed Vercel functions receive a short-lived OIDC token automatically.
	// Pass this store ID explicitly so the SDK does not select the public
	// case-image store from BLOB_STORE_ID.
	if (process.env.VERCEL_OIDC_TOKEN && env.PRIVATE_AVATAR_STORE_ID) {
		return { storeId: env.PRIVATE_AVATAR_STORE_ID };
	}

	// Local development has no Vercel OIDC token, so it requires the static
	// private-store token generated by the Vercel Blob connection.
	if (env.PRIVATE_AVATAR_READ_WRITE_TOKEN) {
		return { token: env.PRIVATE_AVATAR_READ_WRITE_TOKEN };
	}

	throw new AvatarValidationError(
		"Profile photo uploads are not configured yet. Please try again later.",
	);
}

/**
 * Normalizes an uploaded image to a small WebP square. Re-encoding verifies the
 * actual bytes (rather than trusting the browser-provided MIME type) and strips
 * EXIF/other embedded metadata before private storage.
 */
export async function storePrivateAvatar(userId: string, file: File) {
	const blobAuth = privateAvatarBlobAuth();

	if (
		!AVATAR_ACCEPTED_TYPES.includes(
			file.type as (typeof AVATAR_ACCEPTED_TYPES)[number],
		)
	) {
		throw new AvatarValidationError(
			"Choose a JPG, PNG, or WebP image for your profile photo.",
		);
	}

	if (file.size > AVATAR_MAX_BYTES) {
		throw new AvatarValidationError(
			"That image is too large. Choose a JPG, PNG, or WebP under 2 MB.",
		);
	}

	const input = Buffer.from(await file.arrayBuffer());
	let normalized: Buffer;
	try {
		const image = sharp(input, {
			failOn: "error",
			limitInputPixels: 16_000_000,
		});
		const metadata = await image.metadata();
		if (!metadata.format || !AVATAR_SOURCE_FORMATS.has(metadata.format)) {
			throw new AvatarValidationError(
				"Choose a JPG, PNG, or WebP image for your profile photo.",
			);
		}

		normalized = await image
			.rotate()
			.resize(512, 512, { fit: "cover", position: "attention" })
			.webp({ quality: 82 })
			.toBuffer();
	} catch (error) {
		if (error instanceof AvatarValidationError) throw error;
		throw new AvatarValidationError(
			"We could not process that image. Choose a JPG, PNG, or WebP and try again.",
		);
	}

	return put(profileAvatarBlobPath(userId), normalized, {
		access: "private",
		addRandomSuffix: true,
		contentType: "image/webp",
		cacheControlMaxAge: 60,
		...blobAuth,
	});
}

/** A guard against deleting or fetching a legacy third-party auth image URL. */
export function isManagedPrivateAvatar(
	imageUrl: string | null | undefined,
): imageUrl is string {
	return isManagedPrivateAvatarUrl(imageUrl);
}

/** Blob cleanup is deliberately best-effort; the database remains authoritative. */
export async function deletePrivateAvatar(imageUrl: string | null | undefined) {
	if (!isManagedPrivateAvatar(imageUrl)) return;
	await del(imageUrl, privateAvatarBlobAuth());
}

export async function getPrivateAvatar(imageUrl: string | null | undefined) {
	if (!isManagedPrivateAvatar(imageUrl)) return null;
	return get(imageUrl, { access: "private", ...privateAvatarBlobAuth() });
}
